### ISSUE TITLE
spotify playlist & album

### ISSUE THREAD

**Issue by GabrielSSQ** [Androz2091/discord-player#44] opened 2020-07-11 14:48 UTC
We need play the spotify albums or playlists, pls add(?)

**Comment by Androz2091** [comment] 2020-07-11 16:22
Duplicate of #43

**Closed by Androz2091** 2020-07-11 16:22 UTC

**Comment by GabrielSSQ** [comment] 2020-07-15 00:17
I checked but I did not understand. can you be more descriptive?

**Comment by Androz2091** [comment] 2020-07-15 07:58
Your issue is the same as the 43 one. It's useless to have two identical issues. As 43 was opened before your one 44, I closed it.
