### ISSUE TITLE
V13?

### ISSUE THREAD

**Issue by Kayz-xx** [Androz2091/discord-player#660] opened 2021-08-06 18:15 UTC
**Is your feature request related to a problem? Please describe.**

Since discord-player is on v12 and v13 has much better options, such as slash commands and buttons if its possible do let us know if you plan to swtich to v13 on discord-player
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DemonixDev** [comment] 2021-08-06 18:31
> **Is your feature request related to a problem? Please describe.**
> 
> Since discord-player is on v12 and v13 has much better options, such as slash commands and buttons if its possible do let us know if you plan to swtich to v13 on discord-player
> **Describe the solution you'd like**
> 
> **Describe alternatives you've considered**
> 
> **Additional context**

uh there are already support for v13, `npm i discord-player@dev --` and there will probably release normal stable soon beacuse discord.js v13 just officialy released

**Comment by DemonixDev** [comment] 2021-08-06 18:32
update they are working on stable release, mostly Andromena or Andromeda idk

**Comment by DevAndromeda** [comment] 2021-08-07 04:53
I will mark this as a duplicate of #507

**Closed by DevAndromeda** 2021-08-07 04:53 UTC
Labels: enhancement
