### ISSUE TITLE
100 Tracks+ from Spotify Playlist

### ISSUE THREAD

**Issue by GaryCraft** [Androz2091/discord-player#1082] opened 2022-03-14 02:58 UTC
**Describe the feature you would like**
Spotify playlists provide more than 100 tracks

**Expected behavior**
When providing discord-player search a Spotify playlist, it gives a playlist longer than 100 songs

**Additional context**
Currently if using a Spotify playlist link that has more than 100 tracks, it will only get the first 100

**Comment by DevAndromeda** [comment] 2022-03-14 04:00
Possible duplicate of #1078

**Closed** 2022-08-04 09:10 UTC
Labels: enhancement
