### ISSUE TITLE
EPIPE ( stream.destroy ) error and music stops on skip function

### ISSUE THREAD

**Issue by astrex1969** [Androz2091/discord-player#568] opened 2021-06-30 09:52 UTC
**Describe the bug**
I get EPIPE (stream.destroy) error and the music stops whenever is use  client.player.skip(message);

**To Reproduce**

**Comment by Snowflake107** [comment] 2021-06-30 10:10
duplicate of #378

**Closed by Snowflake107** 2021-06-30 10:10 UTC
Labels: bug
