### ISSUE TITLE
The movie data is retrieved normally, but it is disconnected from the voice channel.

### ISSUE THREAD

**Issue by KohnoseLami** [Androz2091/discord-player#1329] opened 2022-08-28 07:40 UTC
**Describe the bug**

I'm running Node.js on a server that doesn't have root privileges
So everything is done in Node.js inside Miniconda.
I don't know if that's the reason, but I've been able to get track titles and call ffmpeg successfully, but the Bot will not play anything and will disconnect the voice channel.

**To Reproduce**

Create a Bot with a simple connection and playback.
And if I do that in my environment, the audio is cut off, not played.

**Expected behavior**

Play music

**Screenshots**

![image](https://user-images.githubusercontent.com/64224091/187063379-d7190d99-7eef-41d2-9360-e3514d0531d0.png)

**Please complete the following information:**
 - Node Version: 16.13.1
 - Discord Player Version: 5,3,1
 - Discord.js Version: 14.3.0

**Additional context**

If you check the process with the ps x command, you can see that ffmpeg is running, but it's already disconnected from the voice channel.
36389 pts/0    Sl+    0:00 ffmpeg -i - -ss 0 -analyzeduration 0 -loglevel 0 -f s16le -ar 48000 -ac 2 pipe:1

**Comment by KohnoseLami** [comment] 2022-08-28 07:41
There's a warning on the console, but I don't know what it means.
And it doesn't show what's causing it, so if I have a problem, I'll ask for a hint.

**Comment by DevAndromeda** [comment] 2022-08-28 08:09
Could you provide your code snippet as well?

**Comment by retrouser955** [comment] 2022-08-28 08:12
> There's a warning on the console, but I don't know what it means. And it doesn't show what's causing it, so if I have a problem, I'll ask for a hint.

The warning will disappear if you update it to Node.js 18 so I don't think that is related to the error.

**Comment by KohnoseLami** [comment] 2022-08-28 08:49
> Could you provide your code snippet as well?

Okay, code here.
```js
const { Colors, ApplicationCommandOptionType } = require("discord.js")
const { settings } = require("../modules/static");
module.exports = {
    data: {
        name: "play",
        description: "指定した曲を再生します",
        dmPermission: false,
        options: [
            {
                name: "query",
                description: "曲を指定してください",
                type: ApplicationCommandOptionType.String,
                required: true
            }
        ]
    },
    async execute(i) {
        let queue = i.player.queues.get(i.guild.id);
        if (!queue) {
            if (!i.member.voice.channelId) {
                return i.reply({
                    embeds: [
                        {
                            title: "Join",
                            description: "ボイスチャンネルに参加するには、まずあなたがボイスチャンネルに居る必要があります",
                            color: Colors.Red,
                            footer: settings.footer
                        }
                    ],
                    ephemeral: true
                })
            }
            queue = i.player.createQueue(i.guild, {
                metadata: {
                    channel: i.channel
                }
            })
            try {
                if (!queue.connection) await queue.connect(i.member.voice.channel);
            } catch {
                queue.destroy();
                return i.reply({
                    embeds: [
                        {
                            title: "Join",
                            description: "ボイスチャンネルに接続できませんでした",
                            color: Colors.Red,
                            footer: settings.footer
                        }
                    ],
                    ephemeral: true
                })
            }
            await i.channel.send({
                embeds: [{
                    title: "Join",
                    description: `<#${i.member.voice.channelId}> に参加しました`,
                    color: Colors.Green,
                    footer: settings.footer
                }]
            })
        }
        await i.deferReply({ephemeral: false});
        if (!queue.connection) {
            i.followUp({
                embeds: [
                    {
                        title: "Join",
                        description: "Botがボイスチャンネルから切断されています",
                        color: Colors.Red,
                        footer: settings.footer
                    }
                ],
                ephemeral: true
            })
            return queue.destroy();
        }
        const query = i.options.getString("query");
        const track = await i.player.search(query, {
            requestedBy: i.user
        }).then(x => x.tracks[0]);
        if (!track) {
            return i.followUp({
                embeds: [
                    {
                        title: "Play",
                        description: "曲が見つかりませんでした",
                        color: Colors.Red,
                        footer: settings.footer
                    }
                ],
                ephemeral: true
            })
        }
        await queue.play(track);
        await i.followUp({
            embeds: [{
                title: "Play",
                description: `${track.title} をキューに追加しました`,
                color: Colors.Green,
                footer: settings.footer
            }]
        })
    }
}
```

By the way, it worked when I ran it locally on Windows.
I forgot to write.

**Comment by KohnoseLami** [comment] 2022-08-28 08:49
> > There's a warning on the console, but I don't know what it means. And it doesn't show what's causing it, so if I have a problem, I'll ask for a hint.
> 
> The warning will disappear if you update it to Node.js 18 so I don't think that is related to the error.

I see. Thank you.

**Comment by ddemile** [comment] 2023-01-19 10:06
@KohnoseLami I have the same problem

**Comment by skdhg** [comment] 2023-03-04 11:21
it's been a while now, but by chance were you guys using ubuntu 22 when this issue occurred?

**Comment by skdhg** [comment] 2023-03-04 12:02
> > it's been a while now, but by chance were you guys using ubuntu 22 when this issue occurred?
> 
> No, Cent OS6 Running with Node.js in Miniconda

if you are still using discord-player, could you try using the latest version (6.0.0) and see if it persists? If it does, could you run it in debug mode (attaching a `debug` event listener to `player.events`) and see if it shows anything?

**Comment by KohnoseLami** [comment] 2023-03-04 20:52
> if you are still using discord-player, could you try using the latest version (6.0.0) and see if it persists? If it does, could you run it in debug mode (attaching a debug event listener to player.events) and see if it shows anything?

I'll try it.

**Comment by skdhg** [comment] 2023-03-21 17:58
possible duplicate of https://github.com/Androz2091/discord-player/issues/1639 lets discuss there instead

**Closed by skdhg** 2023-03-21 17:58 UTC
Labels: bug
