### ISSUE TITLE
issue with module

### ISSUE THREAD

**Issue by Muzihuzi** [Androz2091/discord-player#119] opened 2020-10-18 00:50 UTC
I was using 2discord-player@^2.3.0
I updated the code to 3.0.0 today without touching it, and there was a problem.

```
F:\teampastel\choa_Rewrite\node_modules\discord-player\src\Player.js:608
        }, this.options.leaveOnEmptyCooldown ?? 0)
                                              ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (F:\teampastel\choa_Rewrite\node_modules\discord-player\index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
```

**Comment by Muzihuzi** [comment] 2020-10-18 00:54
s```
// config
const { token, kdbl_token, YT_api_token, Twilio_id, Twilio_token } = require('./src/config.json')
const db = require('./db/db_connection.js')
const funcs = require('./src/functions.js')

const Discord = require('discord.js')
const fs = require('fs')
const fetch = require('node-fetch')
const bodyParser = require('body-parser')

const client = new Discord.Client()
const { Player } = require('discord-player')
// const talkedRecently = new Set();

client.commands = new Discord.Collection()
client.aliases =  new Discord.Collection()

const player = new Player(client, YT_api_token)
client.player = player
client.filters = require("./src/filter.json")


// client login
client.login(token);
```
Some irrelevant codes have been omitted.

**Comment by jz3r01** [comment] 2020-10-18 03:00
package is broke for now... idk when itll be fixed, if at all :(

**Comment by augustin-laurent** [comment] 2020-10-18 07:53
I got this issue too it don't came from your code but the package itself we need to wait for a fix

**Comment by MrPerfectShot** [comment] 2020-10-18 14:56
Update to Node v14

**Comment by jz3r01** [comment] 2020-10-19 17:00
> Update to Node v14
Did this work for u? @MrPerfectShot

**Comment by MrPerfectShot** [comment] 2020-10-19 17:25
Yes but the package is broken

**Comment by Androz2091** [comment] 2020-11-01 13:28
Duplicate of #122, and the support of Node v12 will be added back in v3.0 :wink:

**Closed by Androz2091** 2020-11-01 13:28 UTC
