### ISSUE TITLE
Error while playing music

### ISSUE THREAD

**Issue by SoulHarsh007** [Androz2091/discord-player#5] opened 2020-02-16 04:40 UTC
Cannot seem to play music shows the error mentioned below:  
TypeError: Cannot convert "null" to int  
TypeError: Cannot convert "null" to int  
/rbd/pnpm-volume/ce908d90-1591-4e68-8e70-6fd0493443ea/node_modules/.registry.npmjs.org/opusscript/0.0.7/node_modules/opusscript/build/opusscript_native_wasm.js:8
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=function(status,toThrow){throw toThrow};Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_HAS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_HAS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_NODE=ENVIRONMENT_HAS_NODE&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMEN
abort(TypeError: Cannot convert "null" to int). Build with -s ASSERTIONS=1 for more info.

**Comment by Androz2091** [comment] 2020-02-16 08:37
@SoulHarsh007 can you send your code please?

**Comment by SoulHarsh007** [comment] 2020-02-16 10:35
> @SoulHarsh007 can you send your code please?

let song;
    if (!args[0]) return message.channel.send(`**Please enter a music**`);

    let aSongIsAlreadyPlaying = client.player.isPlaying(message.guild.id);

    if (aSongIsAlreadyPlaying) {
      // Add the song to the queue
      let song = await client.player.addToQueue(
        message.guild.id,
        args.join(" ")
      );
      message.channel.send(`**${song.name} added to queue **`);
    } else {
      // Else, play the song
      let song = await client.player.play(
        message.member.voice.channel,
        args.join(" ")
      );
      message.channel.send(`**Currently playing ${song.name}**`);
    }

**Comment by SoulHarsh007** [comment] 2020-02-16 10:42
`module.exports = {
  name: "play",
  description: "Ping!",
  async execute(client, message, args) {
    let song;
    if (!args[1]) return message.channel.send(`Please enter a music`);

    let aSongIsAlreadyPlaying = client.player.isPlaying(message.guild.id);

    if (aSongIsAlreadyPlaying) {
      // Add the song to the queue
      let song = await client.player.addToQueue(
        message.guild.id,
        args.slice(1).join(" ")
      );
      message.channel.send(`${song.name} added to queue`);
    } else {
      // Else, play the song
      let song = await client.player.play(
        message.member.voice.channel,
        args.slice(1).join(" ")
      );
      message.channel.send(`Currently playing ${song.name}`);
      song.queue.on("end", () => {
        message.channel.send("**The queue is empty, please add some songs!**");
      });
    }
  }
};`  
I use a command handler and this is all of the code in my **play.js**

**Comment by Androz2091** [comment] 2020-02-16 11:42
Can you send me the value of `args.slice(1).join(" ")` when the error happens?

**Comment by SoulHarsh007** [comment] 2020-02-16 14:26
> Can you send me the value of `args.slice(1).join(" ")` when the error happens?

higher  
Name of music that needs to be played
I am adding additional logs in case you need them: 

> ```

Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot convert "null" to int
      at Object.toWireType (/rbd/pnpm-volume/ce908d90-1591-4e68-8e70-6fd0493443ea/node_modules/opusscript/build/opusscript_native_wasm.js:8:47113)
      at OpusScriptHandler$_encode [as _encode] (eval at new_ (/rbd/pnpm-volume/ce908d90-1591-4e68-8e70-6fd0493443ea/node_modules/opusscript/build/opusscript_native_wasm.js:8:36904), <anonymous>:11:26)
      at OpusScript.encode (/rbd/pnpm-volume/ce908d90-1591-4e68-8e70-6fd0493443ea/node_modules/opusscript/index.js:69:28)
      at Encoder._encode (/rbd/pnpm-volume/ce908d90-1591-4e68-8e70-6fd0493443ea/node_modules/discord.js/node_modules/prism-media/src/opus/Opus.js:55:25)
      at Encoder._transform (/rbd/pnpm-volume/ce908d90-1591-4e68-8e70-6fd0493443ea/node_modules/discord.js/node_modules/prism-media/src/opus/Opus.js:138:30)
      at Encoder.Transform._read (_stream_transform.js:190:10)
      at Encoder.Transform._write (_stream_transform.js:178:12)
      at doWrite (_stream_writable.js:410:12)
      at writeOrBuffer (_stream_writable.js:394:5)
      at Encoder.Writable.write (_stream_writable.js:294:11) } reason: TypeError: Cannot convert "null" to int
    at Object.toWireType (/rbd/pnpm-volume/ce908d90-1591-4e68-8e70-6fd0493443ea/node_modules/opusscript/build/opusscript_native_wasm.js:8:47113)
    at OpusScriptHandler$_encode [as _encode] (eval at new_ (/rbd/pnpm-volume/ce908d90-1591-4e68-8e70-6fd0493443ea/node_modules/opusscript/build/opusscript_native_wasm.js:8:36904), <anonymous>:11:26)
    at OpusScript.encode (/rbd/pnpm-volume/ce908d90-1591-4e68-8e70-6fd0493443ea/node_modules/opusscript/index.js:69:28)
    at Encoder._encode (/rbd/pnpm-volume/ce908d90-1591-4e68-8e70-6fd0493443ea/node_modules/discord.js/node_modules/prism-media/src/opus/Opus.js:55:25)
    at Encoder._transform (/rbd/pnpm-volume/ce908d90-1591-4e68-8e70-6fd0493443ea/node_modules/discord.js/node_modules/prism-media/src/opus/Opus.js:138:30)
    at Encoder.Transform._read (_stream_transform.js:190:10)
    at Encoder.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Encoder.Writable.write (_stream_writable.js:294:11)
```

**Comment by hydraindia** [comment] 2020-02-18 02:38
I think any package is missing.

**Comment by Androz2091** [comment] 2020-02-18 09:48
Yes, I agree with @hydraindia because I'm not able to reproduce the bug...
With the same code:
<img width="579" alt="Capture d’écran 2020-02-18 à 10 47 33" src="https://user-images.githubusercontent.com/42497995/74724191-2c1f8500-523c-11ea-9a91-deff635247d6.png">

**Comment by SoulHarsh007** [comment] 2020-02-18 14:01
No none of the mentioned modules are pending installations.
ps: I had ytdl-core and ffmpeg installed before using this module. 
I also tried reinstalling all of the mentioned modules.

**Comment by hydraindia** [comment] 2020-02-19 02:09
Did you installed `node-opus`?

**Comment by hydraindia** [comment] 2020-02-19 02:12
Time zone sucks it's morning in India and it's night in France.

**Comment by SoulHarsh007** [comment] 2020-02-19 06:10
yes I did @hydraindia

**Comment by hydraindia** [comment] 2020-02-19 06:59
Hmm

**Comment by hydraindia** [comment] 2020-02-19 07:00
Are you using https://glitch.com for hosting?

**Comment by hydraindia** [comment] 2020-02-19 07:22
This issue is not related to this package I also tested your code and it works, there something problem with your hosting or packages.

**Comment by SoulHarsh007** [comment] 2020-02-19 07:24
@hydraindia I am self-hosting my bot!

**Comment by SoulHarsh007** [comment] 2020-02-19 07:26
previously I used glitch to host but now I use self-hosting (my pc os;Win 10 x64 proc: intel i3 4150T @3.00GHz) I had music bot running before switching to this package and discord.js v12

**Comment by hydraindia** [comment] 2020-02-19 10:53
Hmm your problem is really weird

**Comment by SoulHarsh007** [comment] 2020-02-19 11:08
Lol I feel the same!  
Something you might find helpful: ytdl-core and some other dependencies are also in my package.json. I think they might be creating issues with the package in anyway? (Lol that is what I think)

**Comment by hydraindia** [comment] 2020-02-19 11:20
@Androz2091 close this issue

**Comment by SoulHarsh007** [comment] 2020-02-19 11:22
@hydraindia may I know the reason?

**Comment by hydraindia** [comment] 2020-02-19 11:23
Becuase it's not related to any issue with discord-player it's problem with your package

**Comment by hydraindia** [comment] 2020-02-19 11:24
or send your full code and error again

**Comment by Androz2091** [comment] 2020-02-19 11:24
@SoulHarsh007 try to create a new project with the play command only (so with no dependencies except discord.js and discord-player) to check if it works

**Comment by Androz2091** [comment] 2020-02-19 11:28
@hydraindia even if it's related to the packages that @SoulHarsh007 has installed, it's interesting to understand where his problem comes from.

**Comment by hydraindia** [comment] 2020-02-19 11:28
hmm

**Comment by hydraindia** [comment] 2020-02-19 11:31
He is not installing any of the module properly maybe `node-opus`

**Comment by hydraindia** [comment] 2020-02-19 11:34
`npm install discord.js`
`npm install discord-player`
`npm install --global --production windows-build-tool`
`npm install node-opus`
and final ffmpeg-binaries
all things above required for a music bot

**Comment by hydraindia** [comment] 2020-02-19 11:34
and run the third command in Admin CMD

**Comment by Androz2091** [comment] 2020-02-19 11:36
@hydraindia only the master branch of discord.js is supported (`npm i discordjs/discord.js`)

**Comment by hydraindia** [comment] 2020-02-19 11:36
Oh! Sorry!

**Comment by hydraindia** [comment] 2020-02-19 11:39
I have a music bot code using `discord-player` give me 5 minutes to publish that repo

**Comment by SoulHarsh007** [comment] 2020-02-19 11:39
Okie

**Comment by SoulHarsh007** [comment] 2020-02-19 11:39
But can I do this installation stuff later? I cannot access my system at the moment.

**Comment by hydraindia** [comment] 2020-02-19 11:42
Use glitch for testing easy

**Comment by SoulHarsh007** [comment] 2020-02-19 11:43
![IMG_20200219_143812](https://user-images.githubusercontent.com/57407752/74831346-180e7d00-533b-11ea-8bd3-126c5910a0b7.jpg)
Cannot do anything at the moment.

**Comment by hydraindia** [comment] 2020-02-19 11:43
just create a new project

**Comment by SoulHarsh007** [comment] 2020-02-19 11:44
Okie

**Comment by SoulHarsh007** [comment] 2020-02-19 11:44
Want me to invite you there??

**Comment by hydraindia** [comment] 2020-02-19 11:46
If you want you can

**Comment by SoulHarsh007** [comment] 2020-02-19 11:46
Discord id?

**Comment by hydraindia** [comment] 2020-02-19 11:48
HYDROX#8573

**Comment by hydraindia** [comment] 2020-02-19 11:49
525322591796199445

**Comment by SoulHarsh007** [comment] 2020-02-19 11:49
Sent!

**Comment by hydraindia** [comment] 2020-02-19 11:51
https://github.com/hydraindia/discord-music

**Comment by hydraindia** [comment] 2020-02-19 11:53
I will make some improvement in the code later but there is no error

**Comment by hydraindia** [comment] 2020-02-19 11:53
Just clone that in glitch

**Comment by SoulHarsh007** [comment] 2020-02-19 11:59
Well the code from your repo works fine! But why does my code throw those errors?  I will get back to you when I can access my system back 😃
Thanks. :tada:

**Comment by hydraindia** [comment] 2020-02-19 12:09
Because of package, the issue you with your code was node-opus or opusscript was not installed properly on your system

**Comment by SoulHarsh007** [comment] 2020-02-19 12:10
Okay. Thanks!

**Comment by SoulHarsh007** [comment] 2020-02-19 12:11
Okay. Thanks!

**Comment by hydraindia** [comment] 2020-02-19 13:03
@Androz2091 I think now issue is solve

**Closed** 2020-02-19 13:04 UTC
