### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by RaymondJiang1** [Androz2091/discord-player#116] opened 2020-10-16 15:01 UTC
It just doesn't work in general :(

**Comment by Cyanitem** [comment] 2020-10-17 06:29
Yeah

**Comment by TisRyno** [comment] 2020-10-24 15:56
Two libraries required by discord-player were removed, see -
https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md

**Comment by Androz2091** [comment] 2020-11-01 13:27
Duplicate of #122

**Closed by Androz2091** 2020-11-01 13:27 UTC
