### ISSUE TITLE
Player does not work on one system but does on another

### ISSUE THREAD

**Issue by samusaran** [Androz2091/discord-player#1665] opened 2023-03-08 13:16 UTC
**Describe the bug**
On my dev machine (windows), the player works fine. But when pull the same code to another machine (centos stream) the songs ends without starting

**To Reproduce**
I don't know. I'm asking for support since I don't know what's missing

**Expected behavior**
Song plays fine

**Error Log**
```
0|discord- | Dispatching audio...
0|discord- | Player triggered for Track {"title":"A HA - TAKE ON ME - SHITTYFLUTED","reason":"normal"}
0|discord- | state change:
0|discord- | from {"status":"buffering","resource":true,"stepTimeout":false}
0|discord- | to {"status":"playing","missedFrames":0,"playbackDuration":0,"resource":true,"stepTimeout":false}
0|discord- | [NW] [WS] >> {"op":5,"d":{"speaking":1,"delay":0,"ssrc":253542}}
0|discord- | [NW] [WS] >> {"op":5,"d":{"speaking":0,"delay":0,"ssrc":253542}}
0|discord- | Track {"title":"A HA - TAKE ON ME - SHITTYFLUTED","isTransitionMode":false} was marked as finished
```

**Please complete the following information:**
 - Node Version: 16.10.0
 - Discord Player Version: 6.0.0
 - Discord.js Version: 14.7.1

**Additional context**
My package.json contains the following packages:
```
  "dependencies": {
    "@discord-player/extractor": "^4.1.0",
    "@discord-player/equalizer": "^0.2.0",
    "@discordjs/opus": "^0.8.0",
    "@discordjs/voice": "^0.14.0",
    "discord-player": "^6.0.0",
    "discord.js": "^14.0.0",
    "dotenv": "^10.0.0",
    "ffmpeg-static": "^4.4.1",
    "opusscript": "^0.0.8",
    "play-dl": "^1.9.6",
    "prism-media": "^1.3.5",
    "slash-create": "^4.0.1",
    "soundcloud-scraper": "^5.0.3"
  }
```

**Comment by skdhg** [comment] 2023-03-08 13:20
possible relation with https://github.com/Androz2091/discord-player/issues/1639

**Comment by skdhg** [comment] 2023-03-15 13:05
closing this as a duplicate of https://github.com/Androz2091/discord-player/issues/1639

**Closed by skdhg** 2023-03-15 13:05 UTC
Labels: bug
