### ISSUE TITLE
error music

### ISSUE THREAD

**Issue by LucasPanais** [Androz2091/discord-player#704] opened 2021-08-16 09:39 UTC
Error: Cannot play a resource that has already ended.
    at AudioPlayer.play (/home/pi/PanaiS/node_modules/@discordjs/voice/dist/audio/AudioPlayer.js:194:19)
    at StreamDispatcher.<anonymous> (/home/pi/PanaiS/node_modules/discord-player/dist/VoiceInterface/StreamDispatcher.js:172:30)
    at Generator.next (<anonymous>)
    at /home/pi/PanaiS/node_modules/discord-player/dist/VoiceInterface/StreamDispatcher.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/pi/PanaiS/node_modules/discord-player/dist/VoiceInterface/StreamDispatcher.js:4:12)
    at StreamDispatcher.playStream (/home/pi/PanaiS/node_modules/discord-player/dist/VoiceInterface/StreamDispatcher.js:165:16)
    at Timeout._onTimeout (/home/pi/PanaiS/node_modules/discord-player/dist/Structures/Queue.js:671:33)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
Error: Did not enter state ready within 20000ms
    at Timeout.<anonymous> (/home/pi/PanaiS/node_modules/@discordjs/voice/dist/util/entersState.js:17:49)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

**Please complete the following information:**
 - Node Version: [16.6.2]
 - Discord Player Version: [5.0.2]
 - Discord.js Version: [13.1.0]

**Comment by DevAndromeda** [comment] 2021-08-16 09:40
duplicate of #696

**Comment by LucasPanais** [comment] 2021-08-16 09:41
There are two mistakes not only one. Also the other person never answers his ticket

**Closed by DevAndromeda** 2021-08-16 09:40 UTC
Labels: bug, duplicate
