### ISSUE TITLE
Issues with modules

### ISSUE THREAD

**Issue by augustin-laurent** [Androz2091/discord-player#118] opened 2020-10-17 20:11 UTC
Hello, I'm currently trying to make a bot with your library cause with the quarantine I'm kinda bored.
I just finish to make the structure of my bot and when I try to pop a sound with a command I create my terminal says me that there is an error in your script.

/Users/augustin/Downloads/Tomy/node_modules/discord-player/src/Player.js:207
                if (results.items.length < 1) return resolve([])
                            ^

TypeError: Cannot read property 'items' of undefined
    at /Users/augustin/Downloads/Tomy/node_modules/discord-player/src/Player.js:207:29
    at /Users/augustin/Downloads/Tomy/node_modules/ytsr/lib/main.js:45:14
    at IncomingMessage.<anonymous> (/Users/augustin/Downloads/Tomy/node_modules/ytsr/lib/util.js:261:7)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

I'm currently running on macOS 11.0 with the latest NodeJS releases to this date.
I link you the code I used that make this error code

`const emotes = require ("../config/emojis.json");
const Discord = require("discord.js")

exports.run = async (client, message, args) => {

    //If the member is not in a voice channel
    if(!message.member.voice.channel) return message.channel.send(`Tu n'es pas dans un canal vocal ${emotes.error}`);

    //If no music is provided
    if (!args[0]) return message.channel.send(`Specifiez une musique à jouer ${emotes.error}`);

    const aTrackIsAlreadyPlaying = client.player.isPlaying(message.guild.id);

        //If there's already a track playing 
        if(aTrackIsAlreadyPlaying){

            //Add the track to the queue
            const result = await client.player.addToQueue(message.guild.id, args.join(" ")).catch(() => {});
            if(!result) {
                message.member.voice.channel.leave()
                return message.channel.send(`Cette plateforme n'est pas supportée.`)
            };

            if(result.type === 'playlist'){
                message.channel.send(`${result.tracks.length} musique(s) ajoutée(s) ${emotes.music}`);
            } else {
                message.channel.send(`${result.name} ajouté à la file d'attente ${emotes.music}`);
            }

        } else {

            //Else, play the song
            const result = await client.player.play(message.member.voice.channel, args.join(" ")).catch(() => {});
            if(!result) {
                message.member.voice.channel.leave()
                return message.channel.send(`Cette plateforme n'est pas supportée.`)
            };

            if(result.type === 'playlist'){
                message.channel.send(`${result.tracks.length} musique(s) ajoutée(s) ${emotes.music}\nJoue actuellement ${result.tracks[0].name}`);
            } else {
                message.channel.send(`Joue actuellement ${result.name} ${emotes.music}`);
            }

            const queue = client.player.getQueue(message.guild.id)

            //Events
            .on('end', () => {
                message.channel.send(`Il n'y a plus de musique dans la file d'attente ${emotes.error}`);
            })
            .on('trackChanged', (oldTrack, newTrack) => {
                message.channel.send(`Joue maintenant ${newTrack.name} ... ${emotes.music}`);
            })
            .on('channelEmpty', () => {
                message.channel.send(`Musique arrêté, il n'y a plus personne dans le canal audio ${emotes.error}`);
            });
        }
    }
`

And as you saw if your read the code, j'apprécie ton travail et j'espère pouvoir sincèrement faire fonctionner ton module dans mon projet.
Ça impressionnera ces donzelle à la Daurade avant le couvre-feu de 21H

**Comment by jz3r01** [comment] 2020-10-17 22:27
As of rn, the package is broken due to some issues that recently occurred... Androz, the creator, hasn't responded to anyone as of yet so for now its a waiting game for him to fix the package.

**Comment by augustin-laurent** [comment] 2020-10-18 07:55
> As of rn, the package is broken due to some issues that recently occurred... Androz, the creator, hasn't responded to anyone as of yet so for now its a waiting game for him to fix the package.

Do you know if a previous version is working or it's broken too ?

**Comment by jz3r01** [comment] 2020-10-18 11:37
> > As of rn, the package is broken due to some issues that recently occurred... Androz, the creator, hasn't responded to anyone as of yet so for now its a waiting game for him to fix the package.
> 
> Do you know if a previous version is working or it's broken too ?
> 
> 

Ive tried 2 or 3 versions... They all don't work. Safe to say all of them don't at that point

**Comment by augustin-laurent** [comment] 2020-10-18 11:41
> > > As of rn, the package is broken due to some issues that recently occurred... Androz, the creator, hasn't responded to anyone as of yet so for now its a waiting game for him to fix the package.
> > 
> > 
> > Do you know if a previous version is working or it's broken too ?
> 
> Ive tried 2 or 3 versions... They all don't work. Safe to say all of them don't at that point

I just downgrade to version 2.3.0 with a base code from Music-bot-master repo, no error on terminal just got to figure out how to make the command play work I can link you the code if you want to check out

**Comment by Androz2091** [comment] 2020-11-01 13:29
Duplicate of #122

**Closed by Androz2091** 2020-11-01 13:29 UTC
