### ISSUE TITLE
Cannot read properties of undefined (reading 'items')

### ISSUE THREAD

**Issue by OXYDE670** [Androz2091/discord-player#1481] opened 2022-12-24 14:48 UTC
hello I discovered a bug on the module when I put a spotify playlist it rejects this error please help me 

at Player.search (/home/container/node_modules/discord-player/dist/Player.js:432:62)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by NerdyTechy** [comment] 2022-12-24 18:15
Duplicate of #1449

**Closed** 2023-01-12 16:03 UTC
Labels: bug
