### ISSUE TITLE
[BUG] Error: write EPIPE

### ISSUE THREAD

**Issue by NotroDev** [Androz2091/discord-player#378] opened 2021-04-30 11:46 UTC
When I use **!filter** this error is sent - _Error: opus stream: write EPIPE_
But filter was added.

**To Reproduce**
1. Use any filter

**Expected behavior**
2. No error
3. 

**Please complete the following information:**
 - Node Version: node 12.22.1
 - Library Version: discord-player 4.0.5
 - Discord.js Version: discord.js 12.5.3

**Additional context**
I don't know what script to send, please write in the comments if you need one
And also, if I don't use `const ytdl = require ('ytdl-core');` I have a `stream destroy` error or something ...

Full Error:
`Error: opus stream: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}`

**Comment by Snowflake107** [comment] 2021-04-30 13:02
Hi, I am unable to reproduce your bug, everything works good for me

![image](https://user-images.githubusercontent.com/46562212/116698749-74136d80-a9e4-11eb-8ebe-e502b43ecda1.png)

**Comment by Snowflake107** [comment] 2021-04-30 17:37
Nothing too fancy in my code, but if you really wanna check it, **[here is the link](https://github.com/Erbiumbot/Erbium)**

**Comment by NotroDev** [comment] 2021-04-30 18:04
> Nothing too fancy in my code, but if you really wanna check it, **[here is the link](https://github.com/Erbiumbot/Erbium)**

I mean my script 😅

**Comment by SuperSweatyTejas** [comment] 2021-05-04 23:30
Im getting the same error from just basic skipping / playing etc

**Comment by Snowflake107** [comment] 2021-05-07 06:49
>Hello, you can catch that error with **[Player#error](https://discord-player.js.org/#/docs/main/master/class/Player?scrollTo=e-error)** event. Also, in some cases, using `filter: "audioonly"` fixed the issue.
>
> You can supply the `filter` option from **[PlayerOptions](https://discord-player.js.org/#/docs/main/master/typedef/PlayerOptions)**

```js
const player = new Player(client, {
    ytdlDownloadOptions: {
        filter: "audioonly"
    }
})
```

**Comment by Samiul30** [comment] 2021-05-08 09:24
:warning: - Something went wrong ... Error : Error: opus stream: write EPIPE I got this error.

**Comment by Klairm** [comment] 2021-05-09 12:03
Even if the error is thrown, does the bot still working? Like if the error happens when you try to play a track, it throws the error message but it will play the song anyways? If so maybe this issue is the same issue as in #392 

What I did meanwhile is log the error in the console using the events so it won't be annoying the text channel

**Comment by Samiul30** [comment] 2021-05-09 12:06
> Even if the error is thrown, does the bot still working? Like if the error happens when you try to play a track, it throws the error message but it will play the song anyways? If so maybe this issue is the same issue as in #392 
> 
> What I did meanwhile is log the error in the console using the events so it won't be annoying the text channel

Yes the bot works. But I want to fix it? Do you know the reason or anything? For which package it is generating?

**Comment by Snowflake107** [comment] 2021-05-09 12:06
I am unable to reproduce the `Error: opus stream: write EPIPE` error, however `Error: input stream: write EPIPE` occurs in few songs.

**Comment by Snowflake107** [comment] 2021-05-09 12:09
And as @Klairm said, this seems to be the issue with Linux pipes because I haven't seen this error in windows

**Comment by Samiul30** [comment] 2021-05-09 12:12
I am hosting the bot in cloud platform and I am getting this issue whenever I add any playlist to play either it is YT or Spotify. ![Screenshot_2021-05-09-18-11-18-945_com.discord.jpg](https://user-images.githubusercontent.com/70639872/117571836-08bb5100-b0f2-11eb-9e15-e9194781c0be.jpg)

And yes this err is not generating in windows.

**Comment by Klairm** [comment] 2021-05-09 12:15
> I am hosting the bot in cloud platform and I am getting this issue whenever I add any playlist to play either it is YT or Spotify. ![Screenshot_2021-05-09-18-11-18-945_com.discord.jpg](https://user-images.githubusercontent.com/70639872/117571836-08bb5100-b0f2-11eb-9e15-e9194781c0be.jpg)
> 
> And yes this err is not generating in windows.

Yes so this seems to be the same as #392  I suggest you to log the error in  the console so it won't be spamming the text channel, it's either a  fffmpeg problem with the linux pipes, or maybe in the discord-player code it could be somehow dispatched, but I'm not sure so as I said use the [error event](https://discord-player.js.org/#/docs/main/master/class/Player?scrollTo=e-errorl) to log throw it on console or just to ignore it.

**Comment by DeathMario** [comment] 2021-05-09 23:02
update to node.js 14x or up @NotroDev

**Comment by DeathMario** [comment] 2021-05-10 15:52
With DP_REPL_CHECK enabled when i play some songs it says error write epipe @Androz2091

**Comment by DeathMario** [comment] 2021-05-11 06:31
> > With DP_REPL_NOCHECK enabled when i play some songs it says error write epipe @Androz2091
> 
> repl.it issue I guess?

Yes im using repl

**Comment by NotroDev** [comment] 2021-05-12 09:13
> > With DP_REPL_NOCHECK enabled when i play some songs it says error write epipe @Androz2091
> 
> repl.it issue I guess?

Im using too, and I and I don't think I can update node.js myself. Sorry for the late reply, I forgot about it

**Comment by DeathMario** [comment] 2021-05-12 16:40
> > > With DP_REPL_NOCHECK enabled when i play some songs it says error write epipe @Androz2091
> > 
> > 
> > repl.it issue I guess?
> 
> Im using too, and I and I don't think I can update node.js myself. Sorry for the late reply, I forgot about it

Yes, you can update node.js version on Repl.it Here its the link https://replit.com/talk/learn/Nodejs-14/85501

**Comment by NotroDev** [comment] 2021-05-12 17:25
Thanks, I installed, but there is still an error. But I don't know if I did this good, because after typing `node -v` it's still version 12: /

**Comment by Klairm** [comment] 2021-05-14 16:59
> 
> 
> Thanks, I installed, but there is still an error. But I don't know if I did this good, because after typing `node -v` it's still version 12 :/

If you write nodejs instead of node, does it work?

**Comment by saambell** [comment] 2021-05-15 02:27
> > Hello, you can catch that error with **[Player#error](https://discord-player.js.org/#/docs/main/master/class/Player?scrollTo=e-error)** event. Also, in some cases, using `filter: "audioonly"` fixed the issue.
> > You can supply the `filter` option from **[PlayerOptions](https://discord-player.js.org/#/docs/main/master/typedef/PlayerOptions)**
> 
> ```js
> const player = new Player(client, {
>     ytdlDownloadOptions: {
>         filter: "audioonly"
>     }
> })
> ```

Thanks, I'm using Node v14 and I was still having the same issue in some videos, but this solution worked for me.

All songs that were having the problem before worked perfectly after the filter was added .

**Comment by NotroDev** [comment] 2021-05-15 12:00
> > Thanks, I installed, but there is still an error. But I don't know if I did this good, because after typing `node -v` it's still version 12 :/
> 
> If you write nodejs instead of node, does it work?

![image](https://user-images.githubusercontent.com/77281214/118359943-da23f700-b585-11eb-9a2f-686bf2766d0d.png)

**Comment by DeathMario** [comment] 2021-05-17 14:34
> > > Thanks, I installed, but there is still an error. But I don't know if I did this good, because after typing `node -v` it's still version 12 :/
> > 
> > 
> > If you write nodejs instead of node, does it work?
> 
> ![image](https://user-images.githubusercontent.com/77281214/118359943-da23f700-b585-11eb-9a2f-686bf2766d0d.png)

sorry for the late response but when you installed the bash script, you need to always run the bot from it. in .replit file just add `run="bash name.sh"` and if you dont have nodejs 14 installed it will install it, and if you have it, it will run your bot with nodejs 14

**Comment by Madnesssik** [comment] 2021-05-18 16:02
Okay guys, if anyone found a bug when using a discord-player on replit first of all 

Make an file named `.replit` and put this script inside:

```
run="bash node.sh"
```

It will change u start script from default to node.sh

Make an file named `node.sh` and put this script inside:

```
export NVM_DIR=/home/runner/nvm
export NODE_VERSION=14

if ! ls $NVM_DIR > /dev/null 2>&1 
then mkdir -p $NVM_DIR
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
fi

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
nvm use $NODE_VERSION

# You may want to run this if you change node version
rm -rf node_modules/
npm i

# install a custom npm version
if [ $(npm -v) != "6.14.9" ]
then npm i -g npm@6.14.9
fi

#just to check if any package is missing
npm outdated | grep "MISSING"
if [ $? -eq 0 ]
then npm i
fi

node .```

It will change u nodejs version from 12 to 14+ and reinstall packages to newest node when u get error after first start type:
 `npm i opusscript`
 
 It should fix your issues with EPIPE [I tried it rn and it fixes the bug]
 
 No problem!
 
 Regards,
 Madnessik

**Comment by Tegnio** [comment] 2021-05-19 11:04
I've discovered that this bug happens only if the search query is a youtube link, any ideas how to fix that?

**Comment by Samiul30** [comment] 2021-05-19 11:34
> I've discovered that this bug happens only if the search query is a youtube link, any ideas how to fix that?

In this case it will be random song, which have no permissions to play in 3rd party website other than yt.

**Comment by muhitrhn** [comment] 2021-06-08 04:21
Anyone knows a fix for this error?

An error occurred... Code: `Error: input stream: write EPIPE`

This error shows after playing the music for 7 hours using queue looping and the music stops but the bot doesn’t leave vc.
I have tried adding this line in player but didn’t help and made the music fully laggy.
```
ytdlDownloadOptions: {
        filter: "audioonly"
    }
```

**Comment by Snowflake107** [comment] 2021-06-17 18:24
Alright, I'm leaving this here. 

![image](https://user-images.githubusercontent.com/46562212/122452870-71d39580-cfc9-11eb-99df-5ec9f68b4a4c.png)

**Comment by Samiul30** [comment] 2021-06-17 18:46
> Alright, I'm leaving this here. 
> 
> ![image](https://user-images.githubusercontent.com/46562212/122452870-71d39580-cfc9-11eb-99df-5ec9f68b4a4c.png)

Then update it with youtube-dl

**Comment by muhitrhn** [comment] 2021-06-17 19:48
> Alright, I'm leaving this here.
> 
> ![image](https://user-images.githubusercontent.com/46562212/122452870-71d39580-cfc9-11eb-99df-5ec9f68b4a4c.png)

Which music bot example? Can you please pass the link? @Snowflake107

**Comment by Snowflake107** [comment] 2021-06-18 03:19
> > Alright, I'm leaving this here.
> > ![image](https://user-images.githubusercontent.com/46562212/122452870-71d39580-cfc9-11eb-99df-5ec9f68b4a4c.png)
> 
> Then update it with youtube-dl

It's not that easy to switch to something else because a lot of things might go wrong. We have to first discuss this.

**Comment by Snowflake107** [comment] 2021-06-18 03:19
> > Alright, I'm leaving this here.
> > ![image](https://user-images.githubusercontent.com/46562212/122452870-71d39580-cfc9-11eb-99df-5ec9f68b4a4c.png)
> 
> Which music bot example? Can you please pass the link? @Snowflake107

The music bot example is from **[@discordjs/voice](https://github.com/discordjs/voice)**

**Comment by Samiul30** [comment] 2021-06-21 16:54
https://www.youtube.com/watch?v=zGd7BBorCKA
https://www.youtube.com/watch?v=x3hhOW28fw8
This two url produce the bug

**Comment by muhitrhn** [comment] 2021-06-21 17:14
> https://www.youtube.com/watch?v=zGd7BBorCKA
> https://www.youtube.com/watch?v=x3hhOW28fw8
> This two url produce the bug

There are plenty more videos which generates this error. As it’s an open source project and uses ytdl, these errors are acceptable. Be okay with it or develop own music system using youtube-dl

**Comment by Samiul30** [comment] 2021-06-21 17:59
> > https://www.youtube.com/watch?v=zGd7BBorCKA
> > https://www.youtube.com/watch?v=x3hhOW28fw8
> > This two url produce the bug
> 
> There are plenty more videos which generates this error. As it’s an open source project and uses ytdl, these errors are acceptable. Be okay with it or develop own music system using youtube-dl 

This error is related to unstable ffmpeg. You may knwo that  >_<

**Comment by Tegnio** [comment] 2021-06-21 18:12
> > > https://www.youtube.com/watch?v=zGd7BBorCKA
> > > https://www.youtube.com/watch?v=x3hhOW28fw8
> > > This two url produce the bug
> > 
> > 
> > There are plenty more videos which generates this error. As it’s an open source project and uses ytdl, these errors are acceptable. Be okay with it or develop own music system using youtube-dl
> 
> This error is related to unstable ffmpeg. You may knwo that >_<

No, this is an issue with ytdl. By the way, discord-player v5 that's built on discord.js new voice library has solved this problem for me.

**Comment by muhitrhn** [comment] 2021-06-21 19:52
> > > > https://www.youtube.com/watch?v=zGd7BBorCKA
> > > > https://www.youtube.com/watch?v=x3hhOW28fw8
> > > > This two url produce the bug
> > > 
> > > 
> > > There are plenty more videos which generates this error. As it’s an open source project and uses ytdl, these errors are acceptable. Be okay with it or develop own music system using youtube-dl
> > 
> > 
> > This error is related to unstable ffmpeg. You may knwo that >_<
> 
> No, this is an issue with ytdl. By the way, discord-player v5 that's built on discord.js new voice library has solved this problem for me.

You mean the @dev branch? Shall i update maybe?

**Comment by Snowflake107** [comment] 2021-06-22 03:57
Dev version is not ready for production. However, you can test it with `npm install discord-player@dev`

**Comment by DragonTahmid1** [comment] 2021-06-26 22:07
i'm getting this error in every 2 songs and i tested dev branch but i was getting errors so any other solution (i had problem installing node 14x too in replit)

**Comment by DragonTahmid1** [comment] 2021-06-26 22:30
navigating in github  i saw the #392 and used 

`ytdlDownloadOptions: {
        filter: "audioonly"
    }`

this works, plays any song without any error :)  ty @Snowflake107

**Comment by DragonTahmid1** [comment] 2021-06-27 10:32
but... This occurs when i stop or skip a song...

**Comment by Samiul30** [comment] 2021-07-26 13:48
error - Something went wrong ... Error : Error: input stream: write EPIPE
How to solve this one or why this err occured?

**Comment by DevAndromeda** [comment] 2021-08-07 15:44
Handling `error` event in v5 will catch this error. I can't say that v5 will get rid of this completely because this can happen due to several reasons but it should reduce this error :+1:

**Closed** 2021-08-07 19:23 UTC
Labels: bug
