### ISSUE TITLE
No Results Error with YouTube Link

### ISSUE THREAD

**Issue by alima566** [Androz2091/discord-player#567] opened 2021-06-28 18:54 UTC
**Describe the bug**
When requesting a song via a YouTube link, it gives me a "No results" error.

**Expected behavior**
As it's a valid YouTube link, the song should immediately play and not result in a "No results" error.

**Screenshots**
![image](https://user-images.githubusercontent.com/14950662/123688787-ae945d80-d80f-11eb-89ea-6b51eaa8357b.png)

**Please complete the following information:**
 - Node Version: 14.16.0
 - Discord Player Version: discord-player@4.1.4
 - Discord.js Version: 12.5.3

**Comment by Snowflake107** [comment] 2021-06-28 18:55
duplicate of #565

**Closed by Snowflake107** 2021-06-28 18:55 UTC
Labels: bug
