### ISSUE TITLE
DJS v13

### ISSUE THREAD

**Issue by alima566** [Androz2091/discord-player#649] opened 2021-08-04 16:10 UTC
**Question**
Is there a stable, working version of this package that uses djs v13 that we can use?

**Comment by Deadr3amer** [comment] 2021-08-05 09:15
> **Question**
> Is there a stable, working version of this package that uses djs v13 that we can use?

Discord-Player is not officially supporting DJS v13. However, you can try the development release of it, by using: 
`npm i discord-player@dev`
Remember, that this is only the development release. It isn't stable and there may be bugs.

**Comment by alima566** [comment] 2021-08-05 14:47
> Discord-Player is not officially supporting DJS v13. However, you can try the development release of it, by using:
So do you mean that even once djs v13 is finally officially released, you won't supporting it? Or do you mean it's not officailly supported as of right now, but will be in the future?

**Comment by DevAndromeda** [comment] 2021-08-05 15:05
discord player will support discord.js v13

**Comment by DevAndromeda** [comment] 2021-08-05 15:05
see #515 for more info

**Comment by DevAndromeda** [comment] 2021-08-07 04:54
I will mark this as a duplicate of #507

**Closed by DevAndromeda** 2021-08-07 04:54 UTC
Labels: question
