### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'intents')

### ISSUE THREAD

**Issue by Korgen1** [Androz2091/discord-player#1012] opened 2022-01-21 20:38 UTC
```
/home/ubuntu/Bot/node_modules/discord-player/dist/Player.js:47
        if (!new discord_js_1.Intents(this.client.options.intents).has(discord_js_1.Intents.FLAGS.GUILD_VOICE_STATES)) {
                                                          ^

TypeError: Cannot read properties of undefined (reading 'intents')
    at new Player (/home/ubuntu/Bot/node_modules/discord-player/dist/Player.js:47:59)
    at Object.<anonymous> (/home/ubuntu/Bot/client/player.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/ubuntu/Bot/commands/play.js:3:16) // 
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```
I get this in my console. 

client is defined in `player.js` as `const client = require("../index.js");`

intents are declared in `index.js` as `const client = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_VOICE_STATES] });`

Using discord.js@13.6.0, discord-player@5.2.0 and node@16.1.0

**Comment by LePtitMetalleux** [comment] 2022-01-21 21:06
see #915

**Comment by DevAndromeda** [comment] 2022-01-31 11:56
duplicate of #915

**Closed by DevAndromeda** 2022-01-31 11:56 UTC
Labels: bug
