### ISSUE TITLE
play / pause doesn't work.

### ISSUE THREAD

**Issue by Xapu1337** [Androz2091/discord-player#303] opened 2021-02-26 06:23 UTC
When pausing the current song i can't resume, It just doesn't do anything.

**Comment by Xapu1337** [comment] 2021-02-26 06:24
`case "pause":
                   await client.player.pause(message);
                   client.api.interactions(interaction.id, interaction.token).callback.post({
                   data: {
                       type: 3,
                       data: {
                           flags: 64,
                           content: "✔ | Pausing..."
                       }
                    }
                   });                   
                   break;
               case "resume":
                   await client.player.resume(message);
                   client.api.interactions(interaction.id, interaction.token).callback.post({
                       data: {
                           type: 3,
                           data: {
                               flags: 64,
                               content: "✔ | Resuming..."
                           }
                       }
                   });
                   break;`

**Comment by hands8142** [comment] 2021-02-26 07:07
The same problem happens to me, but I don't know how to solve it. I'm sorry I couldn't be of help.

**Comment by Androz2091** [comment] 2021-02-26 12:48
Duplicate of #252

**Closed by Androz2091** 2021-02-26 12:48 UTC
