### ISSUE TITLE
Music stops before 25 seconds aproximattley

### ISSUE THREAD

**Issue by emanuelindxdv** [Androz2091/discord-player#1692] opened 2023-03-20 08:22 UTC
**Describe the bug**
I have a problem, basically the bot stops playing music after about 20 - 30 seconds and then the botDisconnect event is executed BY ITSELF and the bot leaves the channel, how can I fix it?

**Expected behavior**
Bot stop reproducing music

**Screenshots**
The bot dont log Errors

**Please complete the following information:**
 - Node Version: 18.4.0
 - Discord Player Version: 5.4.0
 - Discord.js Version: 14.8.0

**Comment by emanuelindxdv** [comment] 2023-03-20 08:47
> discord-player v5 on discord.js v14?

Yes

**Comment by GioGio03** [comment] 2023-03-20 09:01
I dont even know it was possible but if you will use v6 this problem will surely be solved

**Comment by skdhg** [comment] 2023-03-20 10:20
This issue has been fixed in v6 and this issue is also a duplicate of https://github.com/Androz2091/discord-player/issues/1630

**Closed by skdhg** 2023-03-20 10:20 UTC
Labels: bug

**Comment by emanuelindxdv** [comment] 2023-03-20 17:10
Now my command dont works.

`module.exports = {
    data: new SlashCommandBuilder()
        .setName("play")
        .setDescription("Play music from YouTube or Spotify")
        .addStringOption(option =>
            option
                .setName("songname")
                .setDescription("Escribe el nombre de la cancion a reproducir")
                .setRequired(true)
        ),
    voiceChannel: true,
    plugin: 'liveMusic',

    async run(client, interaction) {
        await interaction.deferReply();

        const song = interaction.options.getString('songname');
        const res = await player.search(song, {
            requestedBy: interaction.member,
            searchEngine: QueryType.AUTO
        });

        if (!res || !res.tracks.length) return interaction.editReply({ content: `No results found ${interaction.member}... try again ? ❌`, ephemeral: true });

        const queue = await player.createQueue(interaction.guild, {
            metadata: interaction.channel,
            spotifyBridge: true,
            initialVolume: 75,
            leaveOnEnd: true
        });

        try {
            if (!queue.connection) await queue.connect(interaction.member.voice.channel);
        } catch {
            await player.deleteQueue(interaction.guildId);
            return interaction.editReply({ content: `I can't join the voice channel ${interaction.member}... try again ? ❌`, ephemeral: true });
        }

        await interaction.editReply({ content: `Loading your ${res.playlist ? 'playlist' : 'track'}... 🎧` });

        res.playlist ? queue.addTracks(res.tracks) : queue.addTrack(res.tracks[0]);

        if (!queue.playing) await queue.play();
  }
};
`
